### ISSUE TITLE
(임시 이슈) 파트별 초기 점검 진행

### ISSUE THREAD

**Issue by nestiank** [boostcampaitech3/final-project-level3-cv-02#1]
이슈 규칙을 준비하기 전에 작성한 임시 이슈입니다.
관련된 규칙의 적용을 받지 않고, 업데이트되지 않습니다.

### 기한 및 제약 조건

5/17(화) 18:00 ~ 5/19(목) 16:00

#### AI

- [x] 이수아: 사용할 모델을 처음부터 학습시키는 것이 얼마나 걸리는지 확인하고, 사용할 데이터셋을 찾기 (Replaced with #19, #12)
- [x] 김주영: SDEdit의 입력과 출력에 대해 알아보고, 입력의 색깔이 결과물에 반영되도록 하는 방법 찾기 (Replaced with #20)
- [x] 유환규: 이미지 결과물 upscaling 방법 찾기(SRGAN 등을 사용해 보기) (Replaced with #21)

#### 백엔드

- [x] 김예원: FastAPI를 알아보고 React.js 프론트엔드와 연결할 수 있는 방법 공유하기 (Replaced with #22)

#### 5/18(수) 16:00

  * 이수아: 실험 및 탐색을 진행 중임
  * 김주영: 코드에서 발생한 오류를 수정 중임
  * 유환규: 실험 결과(이미지)를 슬랙에 공유함

> 팀원들이 이미지를 같이 본 결과, 그림판으로 4x upscaling한 것보다 ESRGAN을 사용해서 4x upscaling한 것이 훨씬 자연스러웠음. 창문과 창틀의 경계와 같이 인접한 픽셀들이 확연한 색깔 차이를 보이는 경우에는 성능이 좋았고, 베개와 이불의 경계와 같이 색깔 차이가 덜한 경우에는 성능이 조금 떨어졌으나, 여전히 그림판으로 upscaling한 것보다는 훨씬 좋은 결과 이미지를 만들었음.

  * 김예원: FastAPI 공부에 많은 진전이 있음

> 프론트엔드와 연결할 수 있는 방법에 대해서는, 프론트엔드를 맡은 팀원도 관련 공부를 충분히 마칠 수 있도록, 팀 전체가 자신의 파트를 공유하는 날을 따로 잡고, 그 날 공유하기로 했음.

#### 5/19(목) 16:00

  * 이수아: 현실적으로 사용할 수 있는 데이터셋이 없음

> 학습이 유의미하려면 고화질 이미지를 사용해서 학습시켜야 하는데, 데이터셋의 크기를 고려했을 때 GPU 메모리 용량 문제와 디스크 용량 문제가 반드시 모두 발생할 것임.

  * 김주영: 보고된 것처럼 색깔이 반영이 아예 안 되는 건 아닌데, 그게 유의미하기에는 일단 성능이 너무 좋지 않았음

> 녹색 베개를 합성해 달라고 했는데 베개가 없어지거나 빨간 베개를 합성한 경우가 있었음.
> 아예 벽으로 덮어지면서 없어지는 물체도 많이 있었음.
> 창문을 그렸을 때 내가 그린 창틀에 맞춰서 창문을 합성해 주는 것이 아니라, 흔한 창문 사진을 가져와서 잘라서 붙이는 듯한 결과가 나왔음.

  * 김예원: FastAPI를 사용해 보면서 도커 이미지가 있어서 사용해 보려고 했는데, 도커에서 너무 많은 오류를 겪어서, 도커를 사용하지 않는 방법으로 다시 연습해 보고 있음

> 이수아: 프론트엔드 파트의 백엔드 파트로의 진행 상황 공유는 주말까지 웹페이지 작업을 좀 더 한 다음에 진행하는 것이 좋겠음

  * 모델의 성능 관련 논의 (Copied to #20)

> 색깔이 반영되지 않는 문제는 비즈니스 관점에서 비교적 작은 문제임. 내가 그린 물건이 합성된 사진에서 나타나지 않는 경우가 가장 심각한데, 마침 SDEdit은 여러 가지 합성된 이미지를 제안하므로, 이를 해결하기 위해서 영역별로 기존 사진과 가장 유사도가 낮은 사진의 영역을 가져오는 방법이 있음.
> 고화질 이미지가 아니더라도 학습을 하는 것이 불리할 것 같지는 않음.
> 5/20(금) 16:00까지 각자 아이디어를 마련해 오기로 함.
