### ISSUE TITLE
(임시 이슈) 파트별 1차 개발 완료

### ISSUE THREAD

**Issue by nestiank** [boostcampaitech3/final-project-level3-cv-02#2]
이슈 규칙을 준비하기 전에 작성한 임시 이슈입니다.
관련된 규칙의 적용을 받지 않고, 업데이트되지 않습니다.

### 기한 및 제약 조건

5/19(목) 18:00 ~ 5/24(화) 16:00

### 내용

"제출을 할 수는 있는데 부족한 상태"에 도달하기 위한 개발 진행

세부적인 목표는 #1 결과에 따라 확정될 예정

### 중간 점검 로그

5/20(금) 16:00

- [x] 5/23(월) 16:00까지 모두 프로젝트 README 관련 노션 페이지 채우기 (Replaced with #7, #8, #9, #10, #11, #16)
- [x] 5/23(월) 16:00까지 최소 한 명은 SDEdit 공식 레포지토리의 demo용 inference 코드를 리팩토링해서, 이미지 2장의 링크를 입력으로 넣으면 그 이미지들을 다운로드한 뒤 input으로 사용하도록 만들기 (Replaced with #23)
- [x] 5/23(월) 16:00까지 리팩토링된 SDEdit inference 코드(#23)를 사용해서, iteration 관련 기록을 작성하고 공유하면서, 각자 10~20장의 inference 진행하기 (Replaced with #24)
- [x] 5/23(월) 16:00까지 학습을 제외한 모델 성능 개선 방법 관련 아이디어(결과물 후처리 등)를 마련하기 (Replaced with #25)

> 학습을 통한 모델 성능 개선은 #13 을 통해서 진행함
> 원래 당일 논의하기로 하였으나(decided by #20) 미뤄짐
